[server.quic.certificate]
cert_file = "/home/loreserver/certs/cert.pem"
pkey_file = "/home/loreserver/certs/key.pem"

[immutable_store.local]
path = "/home/loreserver/store"
flush_delay_seconds = 10

[mutable_store.local]
path = "/home/loreserver/store"
flush_delay_seconds = 10