code --install-extension akamud.vscode-theme-onedark
code --install-extension angelo-breuer.clock
code --install-extension benjaminbenais.copilot-theme
code --install-extension cjhowe7.laravel-blade
code --install-extension denoland.vscode-deno
code --install-extension docker.docker
code --install-extension dunstontc.vscode-docker-syntax
code --install-extension frenco.vscode-vercel
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension google.geminicodeassist
code --install-extension irongeek.vscode-env
code --install-extension ms-vscode.atom-keybindings
code --install-extension oderwat.indent-rainbow
code --install-extension rafaelmaiolla.diff
code --install-extension ronnidc.nunjucks
