module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 18,
    fontFamily: '"Fira Mono", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    cursorColor: '#3ec7a0',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#ffffff',
    backgroundColor: '#000000',
    selectionColor: 'rgba(62,199,160,0.4)',
    borderColor: '#3ec7a0',
    css: '',
    termCSS: '',
    showHamburgerMenu: true,
    showWindowControls: true,
    padding: '12px 14px',
    colors: {
        black: '#000000',
        red: '#E54B4B',
        green: '#9ECE58',
        yellow: '#FAED70',
        blue: '#396FE2',
        magenta: '#BB80B3',
        cyan: '#2DDAFD',
        white: '#d0d0d0',
        lightBlack: 'rgba(255, 255, 255, 0.2)',
        lightRed: '#FF5370',
        lightGreen: '#C3E88D',
        lightYellow: '#FFCB6B',
        lightBlue: '#82AAFF',
        lightMagenta: '#C792EA',
        lightCyan: '#89DDFF',
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: false,
    copyOnSelect: true,
    defaultSSHApp: true,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {},
};
