#
#
# ~/.bash_profile
# 	- Initial setup required: bash ./linux/bash/bash-setup.sh
#   - Loads other Bash config files
#   - Contains user specific tools and config
#   - Adds command aliases
#   - Sets a custom prompt style
#
#

# Load local environment variable file if it exists
# 	- Expects each line in this file to look like:
# 		export SOMETHING_API_KEY=aaa

[ -e "$HOME/.env.local" ] && source "$HOME/.env.local";

# Load other Bash config files if they exist

[ -e "$HOME/.git_bash_prompt.sh" ] && source "$HOME/.git_bash_prompt.sh";
[ -e "$HOME/.git_bash_autocomplete.sh" ] && source "$HOME/.git_bash_autocomplete.sh";

# Helper function to add a dir to the PATH env var if it's not already there

pathadd() {
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
    PATH="${PATH:+"$PATH:"}$1"
  fi
}

# Update PATH to include user level bin directories if they exist

pathadd "/usr/local/bin"
pathadd "$HOME/bin"
pathadd "$HOME/.local/bin"
pathadd "$HOME/.deno/bin"
pathadd "$HOME/.cargo/bin"

# Deno - Configure if it's installed to the default location

if [ -f "$HOME/.deno/env" ]; then
  source "$HOME/.deno/env"
fi

# FZF - Configure shell integration

if command -v fzf > /dev/null 2>&1; then
	eval "$(fzf --bash)"
fi

# Mise - Configure if it's installed to the default location

if command -v mise > /dev/null 2>&1 && [ -f "$HOME/.local/bin/mise" ]; then
	eval "$($HOME/.local/bin/mise activate bash)"
fi

# Just - Add 'ujust' alias if suitable

if [ -e "$HOME/justfile" ]; then
	alias ujust='just --justfile "$HOME/justfile"'
fi

# NVM - Configure if it's installed to the default location

if [ -d "$HOME/.nvm" ]; then
  export NVM_DIR="$HOME/.nvm"
  source "$HOME/.nvm/nvm.sh" > /dev/null 2>&1
fi

# Homebrew - Search for a current installation

if [ -d "$HOME/.brew" ]; then
  export BREW_DIR="$HOME/.brew"
elif [ -d "/home/linuxbrew/.linuxbrew" ]; then
  export BREW_DIR="/home/linuxbrew/.linuxbrew"
elif [ -d "/opt/homebrew" ]; then
  export BREW_DIR="/opt/homebrew"
elif [ -d "/usr/local" ]; then
  export BREW_DIR="/usr/local"
fi

# Homebrew - Configure and set an appropriate alias command

if [[ "$BREW_DIR" != "" ]]; then
  export HOMEBREW_RELOCATE_BUILD_PREFIX="$BREW_DIR"
  export HOMEBREW_CELLAR="$BREW_DIR/Cellar"
  export HOMEBREW_PREFIX="$BREW_DIR"
	export HOMEBREW_NO_AUTO_UPDATE=1
  export HOMEBREW_NO_UPDATE_REPORT_FORMULAE=1
  export HOMEBREW_NO_UPDATE_REPORT_CASKS=1
  export HOMEBREW_NO_ENV_HINTS=1
  export HOMEBREW_NO_ANALYTICS=1

  pathadd "$BREW_DIR/bin"

  alias brew="$BREW_DIR/bin/brew"
fi

# Set suitable user level shell variables

export SHELL=$(which bash)
export TERM=xterm-256color

# Bash prompt customisations
#   - (date current_dir git_branch new_line > space)
#   - Helpful tools:
#		  - https://robotmoon.com/bash-prompt-generator/
#     - https://bash-prompt-generator.org/
#   - Relies on the '__git_ps1' script from the official Git repo:
#     https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh

PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 " %s")';
PS1=$'\[$(tput setaf 242)\]\D{%I:%M:%S} \[$(tput setaf 247)\]\u \h\[$(tput sgr0)\] \[$(tput setaf 159)\]\w\[$(tput setaf 45)\]${PS1_CMD1}\[$(tput sgr0)\]\n\[$(tput setaf 242)\]> \[$(tput sgr0)\]';

# Aliases - Docker

if command -v docker > /dev/null 2>&1; then
  alias docker-compose='docker compose'
  alias docker-up='docker compose up -d'
  alias docker-down='docker compose down'
  alias docker-ps="docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.ID}}\t{{.Image}}'"
  alias docker-st="docker stats --no-stream --format 'table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.Container}}'"
fi

# Aliases - Folder listing and searching

alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias lah='ls -lah'

# Aliases - Cleaner bash command history

alias hist='history | cut -c 8-'
alias hist-search='history | cut -c 8- | grep'

# Aliases - Zed Editor

if command -v zeditor > /dev/null 2>&1; then
  alias zed='zeditor'
fi
