#!/usr/bin/env just --justfile
#
#
# Just command runner configuration
#   - Initial setup: bash ./setup-just-commands-user.sh
#   - Then you can run from any directory (lists all options): ujust
#   - More info at https://github.com/casey/just
#
#

# Set default config

set shell := ["bash", "-uc"]
set ignore-comments := true
set quiet := true

# Add alias commands

alias what := list

alias update := ubuntu-update
alias update-all := ubuntu-update
alias up := ubuntu-update

alias clean := ubuntu-clean
alias del := ubuntu-clean

# The command used for 'just', set this to the alias if you made it

just-cmd := 'j'

# Default to the 'list' command, run via 'run'

default: list

# Show a list of the available 'run' commands
list:
  echo "Listing commands from {{ justfile() }}"
  just --justfile "{{ justfile() }}" --list --alias-style 'separate' --list-heading '' --list-prefix "{{ just-cmd }} "

# Return your machine's public IP address
ip:
  dig +short myip.opendns.com @resolver1.opendns.com

# Update Ubuntu system packages and apps
ubuntu-update:
  sudo apt update
  sudo apt upgrade -y
  sudo snap refresh
  flatpak update -y
  brew update
  brew upgrade

# Clean Ubuntu packages and temp files
ubuntu-clean:
  sudo apt autoremove
  sudo apt autoclean
  flatpak uninstall -y --unused --delete-data
  brew cleanup
  sudo snap set system refresh.retain=2
  sudo rm -rf /var/lib/snapd/cache/*
  sudo rm -rf /tmp/*
  sudo rm -rf ~/.cache/*
  sudo rm -rf ~/.local/share/Trash/*

# Output details about Just
info:
  echo "$( just --version )"
  echo "process id: {{ just_pid() }}"
  echo "just bin: {{ just_executable() }}"
  echo "justfile dir: {{ justfile_directory() }}"
  echo "invocation dir: {{ invocation_directory() }}"
