#!/usr/bin/env just --justfile
#
#
# Just command runner configuration
#   - Initial setup: bash ./setup-just-commands-user.sh
#   - Then you can run from any directory (lists all options): ujust
#   - More info at https://github.com/casey/just
#
#

# Set sensible default config

set shell := ["bash", "-uc"]
set ignore-comments := true
set quiet := true

# Add alias commands

alias what := list
alias df := dotfiles
alias h := home
alias up := ubuntu-update
alias upbr := brew-update

# Save common dirs to variables

dotfiles-dir := '$(cd "$(dirname "{{ justfile_directory() }}")" && cd .. && pwd)'

# Default to the 'list' command, run via 'run'
default: list

# Show a list of the available 'run' commands
list:
  @echo "Listing commands from {{ justfile() }}"
  @just --list --justfile "{{ justfile() }}" --list-heading '' --list-prefix 'run '

# Change to the dotfiles directory
dotfiles:
  cd {{ dotfiles-dir }}

# Change to the user home directory
home:
  cd "$HOME"

# Update Ubuntu system packages and apps
ubuntu-update:
  sudo apt update
  sudo apt upgrade -y
  sudo snap refresh
  flatpak update -y

# Return your machine's public IP address
ip:
  dig +short myip.opendns.com @resolver1.opendns.com

# Update local Homebrew packages
brew-update:
  brew update
  brew upgrade
  brew cleanup

# Output details about Just
info:
  echo "$( just --version )"
  echo "process id: {{ just_pid() }}"
  echo "just bin: {{ just_executable() }}"
  echo "justfile dir: {{ justfile_directory() }}"
  echo "invocation dir: {{ invocation_directory() }}"
