code --install-extension ms-vscode.atom-keybindings
code --install-extension akamud.vscode-theme-onedark
code --install-extension angelo-breuer.clock
code --install-extension denoland.vscode-deno
code --install-extension ms-vscode-remote.remote-containers
code --install-extension rafaelmaiolla.diff
code --install-extension IronGeek.vscode-env
code --install-extension golang.Go
code --install-extension oderwat.indent-rainbow
code --install-extension cjhowe7.laravel-blade
code --install-extension ronnidc.nunjucks
code --install-extension xdebug.php-debug
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension mohsen1.prettify-json
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension wayou.vscode-todo-highlight
code --install-extension dunstontc.vscode-docker-syntax
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension EditorConfig.EditorConfig
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension BenjaminBenais.copilot-theme