code --install-extension akamud.vscode-theme-onedark
code --install-extension GitHub.vscode-pull-request-github
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ronnidc.nunjucks
code --install-extension HookyQR.beautify
code --install-extension angelo-breuer.clock
code --install-extension cjhowe7.laravel-blade
code --install-extension rafaelmaiolla.diff
code --install-extension dunstontc.vscode-docker-syntax
code --install-extension IronGeek.vscode-env
code --install-extension HashiCorp.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension eg2.vscode-npm-script
code --install-extension bam.vscode-file-templates
code --install-extension oderwat.indent-rainbow
code --install-extension mhutchie.git-graph
code --install-extension golang.Go
code --install-extension denoland.vscode-deno
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension wayou.vscode-todo-highlight