#!/usr/bin/env just --justfile
#
#
# Just command runner configuration
#   - Initial setup: bash ./setup-just-commands-user.sh
#   - Then you can run from any directory (lists all options): ujust
#   - More info at https://github.com/casey/just
#
#

# Set default config

set shell := ["bash", "-uc"]
set ignore-comments := true
set quiet := true

# Add alias commands

alias help := list
alias ls := list
alias menu := choose

# Default to the 'list' command, when 'just' is run without any parameters
default: list

# Show a graphical selector listing the available options and their script content
choose:
  @just --choose --justfile "{{ justfile() }}"

# Show a list of the available 'run' commands
list:
  @echo '{{ style("warning") }}Listing "just" command options from {{ justfile() }}{{ NORMAL }}'
  just --justfile "{{ justfile() }}" --list --alias-style 'right' --list-heading '' --list-prefix ''

# Get the OS name
[group('system')]
os:
  #!/usr/bin/env bash
  OS="$(uname -s)";
  if [[ "$OS" == 'Freedesktop SDK' ]]; then
    echo 'Linux';
  elif [[ "$OS" == 'Linux' ]]; then
    DISTRO_NAME="$(source /etc/os-release && echo $NAME)";
    if [[ "$DISTRO_NAME" == 'Fedora Linux' ]]; then
      echo 'Fedora';
    else
      echo "${DISTRO_NAME}";
    fi
  elif [[ "$OS" == 'Darwin' ]]; then
    echo 'macOS';
  elif [[ "$OS" == 'CYGWIN' || "$OS" == 'MINGW' || "$OS" == 'MSYS_NT' ]]; then
    echo 'Windows';
  else
    echo "${OS}";
  fi

# List local users
[group('system')]
users:
  awk -F: '$3 >= 1000 && $1 != "nobody" && $0="user: " $1 "   id: " $3 "   home: " $6' /etc/passwd

# Find which processes are using a certain port number
[group('system')]
[positional-arguments]
port port_number:
  sudo lsof -i ":{{ port_number }}" || echo "Port doesn't seem to be in use"

# Run 'backup-user' script
[group('tools')]
backup:
  bash "$HOME/Dotfiles/storage/backup-linux-user/backup-linux-user.sh"

# Return your machine's public IP address
[group('tools')]
ip:
  dig +short myip.opendns.com @resolver1.opendns.com

# Update system packages and apps
[group('system')]
update:
  #!/usr/bin/env bash
  OS=$(just os);
  if [[ "$OS" == 'Fedora' ]]; then
    echo '=> Fedora: Requesting sudo';
    sudo -v;
    echo '=> Fedora: Updating packages';
    sudo dnf upgrade --refresh -y > /dev/null 2>&1;
    echo '=> Fedora: Updating firmware';
    sudo fwupdmgr get-updates > /dev/null 2>&1;
    sudo fwupdmgr update -y > /dev/null 2>&1;
  elif [[ "$OS" == 'Ubuntu' ]]; then
    echo '=> Ubuntu: Requesting sudo';
    sudo -v;
    echo '=> Ubuntu: Updating APT packages';
    sudo apt update -y -qq > /dev/null 2>&1;
    sudo apt upgrade -y -qq > /dev/null 2>&1;
    sudo apt full-upgrade -y -qq > /dev/null 2>&1;
  elif [[ "$OS" == 'EndeavourOS' ]]; then
    echo '=> EndeavourOS: System updates';
    sudo pacman -Syu --noconfirm > /dev/null 2>&1;
    echo '=> EndeavourOS: Package updates';
    yay -Sua --noconfirm > /dev/null 2>&1;
  fi
  if command -v snap > /dev/null 2>&1 ; then
    echo '=> Snap: Updating packages';
    sudo snap refresh > /dev/null 2>&1;
  fi
  if command -v flatpak > /dev/null 2>&1 ; then
    echo '=> Flatpak: Updating packages';
    flatpak update -y > /dev/null 2>&1;
  fi
  if command -v brew > /dev/null 2>&1 ; then
    echo '=> Homebrew: Updating packages';
    export HOMEBREW_NO_UPDATE_REPORT_FORMULAE=1
    export HOMEBREW_NO_UPDATE_REPORT_CASKS=1
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_NO_ANALYTICS=1
    brew update > /dev/null 2>&1;
    brew upgrade > /dev/null 2>&1;
  fi

# Clean packages and temp files
[group('system')]
clean:
  #!/usr/bin/env bash
  OS=$(just os);
  if [[ "$OS" == 'EndeavourOS' ]]; then
    echo '=> EndeavourOS: Requesting sudo';
    sudo -v;
    echo '=> EndeavourOS: Cleanup packages';
    paccache -rvk2 > /dev/null 2>&1;
    paccache -ruk0 > /dev/null 2>&1;
    sudo pacman -Rns $(pacman -Qtdq) --noconfirm > /dev/null 2>&1;
    echo '=> EndeavourOS: Empty cache';
    rm -rf "$HOME/.cache/"*;
  elif [[ "$OS" == 'Fedora' ]]; then
    echo '=> Fedora: Requesting sudo';
    sudo -v;
    echo '=> Fedora: Cleanup packages';
    sudo dnf autoremove -y > /dev/null 2>&1;
    sudo dnf clean all > /dev/null 2>&1;
  elif [[ "$OS" == 'Ubuntu' ]]; then
    echo '=> Ubuntu: Cleanup APT packages';
    sudo apt autoremove -y > /dev/null 2>&1;
    sudo apt clean -y > /dev/null 2>&1;
    sudo apt autoclean -y > /dev/null 2>&1;
  fi
  if command -v flatpak > /dev/null 2>&1 ; then
    echo '=> Flatpak: Cleanup cache';
    rm -rf "$HOME/.cache/flatpak"
    mkdir -p "$HOME/.cache/flatpak"
    echo '=> Flatpak: Cleanup packages';
    flatpak uninstall -y --unused --delete-data > /dev/null 2>&1;
  fi
  if command -v brew > /dev/null 2>&1 ; then
    echo '=> Homebrew: Cleanup packages';
    brew cleanup > /dev/null 2>&1;
  fi
  if command -v snap > /dev/null 2>&1 ; then
    echo '=> Snap: Cleanup packages';
    sudo snap set system refresh.retain=2 > /dev/null 2>&1;
    sudo rm -rf '/var/lib/snapd/cache/*' > /dev/null 2>&1;
  fi

# Info about Just and the system
[group('info')]
info:
  @echo "$( just --version )"
  @echo "OS: $( just os )"
  @echo "Architecture: {{ arch() }}"
  @echo "Process: {{ just_pid() }}"
  @echo "Binary: {{ just_executable() }}"
  @echo "Config: {{ justfile() }}"
  @echo "Current Dir: {{ invocation_directory() }}"
