#!/usr/bin/env just --justfile
#
#
# Just command runner configuration
#   - Initial setup: bash ./setup-just-commands-user.sh
#   - Then you can run from any directory (lists all options): ujust
#   - More info at https://github.com/casey/just
#
#

# Set default config

set shell := ["bash", "-uc"]
set ignore-comments := true
set quiet := true

# Add alias commands

alias help := list

# Default to the 'list' command, run via 'run'

default: list

# Show a list of the available 'run' commands
list:
  @echo "----"
  @echo "List of commands from {{ justfile() }}"
  @echo "----"
  just --justfile "{{ justfile() }}" --list --alias-style 'separate' --list-heading '' --list-prefix "just "
  @echo "----"

# List local users
users:
  awk -F: '$3 >= 1000 && $1 != "nobody" && $0="user: " $1 "   id: " $3 "   home: " $6' /etc/passwd

# Find which processes are using a certain port number
[positional-arguments]
port port_number:
  sudo lsof -i ":{{ port_number }}" || echo "Port doesn't seem to be in use"

# Return your machine's public IP address
ip:
  dig +short myip.opendns.com @resolver1.opendns.com

# Update system packages and apps
update:
  sudo apt update
  sudo apt upgrade -y
  sudo snap refresh
  flatpak update -y
  brew update
  brew upgrade

# Clean packages and temp files
clean:
  sudo apt autoremove
  sudo apt autoclean
  sudo snap set system refresh.retain=2
  flatpak uninstall -y --unused --delete-data
  brew cleanup
  gio trash --empty
  sudo rm -rf /var/lib/snapd/cache/*
  sudo rm -rf /tmp/*
  sudo rm -rf ~/.cache/* || true

# Info about Just and the system
info:
  @echo "$( just --version )"
  @echo "OS: {{os()}}"
  @echo "Family: {{os_family()}}"
  @echo "Architecture: {{arch()}}"
  @echo "Process: {{ just_pid() }}"
  @echo "Binary: {{ just_executable() }}"
  @echo "Config: {{ justfile() }}"
  @echo "Current Dir: {{ invocation_directory() }}"
