hotkeys: {}
ssh: {}
terminal:
  colorScheme:
    name: Tomorrow Night Bright
    foreground: '#eaeaea'
    background: '#000000'
    cursor: '#eaeaea'
    colors:
      - '#000000'
      - '#d54e53'
      - '#b9ca4a'
      - '#e7c547'
      - '#7aa6da'
      - '#c397d8'
      - '#70c0b1'
      - '#ffffff'
      - '#000000'
      - '#d54e53'
      - '#b9ca4a'
      - '#e7c547'
      - '#7aa6da'
      - '#c397d8'
      - '#70c0b1'
      - '#ffffff'
  background: colorScheme
  font: Fira Code
  fontSize: 16
  ligatures: true
  copyOnSelect: true
appearance:
  theme: Standard
  tabsLocation: top
  opacity: 1
enableAnalytics: false
